[2025-01-26T09:26:16.213+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T09:26:16.223+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_dag_test.branch manual__2025-01-26T09:26:12.757582+00:00 [queued]>
[2025-01-26T09:26:16.228+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_dag_test.branch manual__2025-01-26T09:26:12.757582+00:00 [queued]>
[2025-01-26T09:26:16.230+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-26T09:26:16.240+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): branch> on 2025-01-26 09:26:12.757582+00:00
[2025-01-26T09:26:16.245+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=930) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T09:26:16.247+0000] {standard_task_runner.py:72} INFO - Started process 932 to run task
[2025-01-26T09:26:16.246+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'final_dag_test', 'branch', 'manual__2025-01-26T09:26:12.757582+00:00', '--job-id', '448', '--raw', '--subdir', 'DAGS_FOLDER/t.py', '--cfg-path', '/tmp/tmpgmwtuodt']
[2025-01-26T09:26:16.248+0000] {standard_task_runner.py:105} INFO - Job 448: Subtask branch
[2025-01-26T09:26:16.276+0000] {task_command.py:467} INFO - Running <TaskInstance: final_dag_test.branch manual__2025-01-26T09:26:12.757582+00:00 [running]> on host 7854821b9569
[2025-01-26T09:26:16.321+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='final_dag_test' AIRFLOW_CTX_TASK_ID='branch' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T09:26:12.757582+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T09:26:12.757582+00:00'
[2025-01-26T09:26:16.322+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T09:26:16.331+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-26T09:26:16.337+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T09:26:16.338+0000] {branch.py:38} INFO - Branch into None
[2025-01-26T09:26:16.339+0000] {skipmixin.py:230} INFO - Following branch ()
[2025-01-26T09:26:16.347+0000] {skipmixin.py:278} INFO - Skipping tasks [('grouping.grouping', -1), ('filtering.filter_by_southeast', -1), ('filtering.filter_by_southwest', -1)]
[2025-01-26T09:26:16.360+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T09:26:16.360+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=final_dag_test, task_id=branch, run_id=manual__2025-01-26T09:26:12.757582+00:00, execution_date=20250126T092612, start_date=20250126T092616, end_date=20250126T092616
[2025-01-26T09:26:16.422+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T09:26:16.434+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T09:26:16.438+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
