[2025-01-20T11:10:30.033+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T11:10:30.044+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_query_dag.fetch_data_from_postgres manual__2025-01-20T11:10:29.293182+00:00 [queued]>
[2025-01-20T11:10:30.049+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_query_dag.fetch_data_from_postgres manual__2025-01-20T11:10:29.293182+00:00 [queued]>
[2025-01-20T11:10:30.049+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-20T11:10:30.058+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_data_from_postgres> on 2025-01-20 11:10:29.293182+00:00
[2025-01-20T11:10:30.064+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=832) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T11:10:30.065+0000] {standard_task_runner.py:72} INFO - Started process 833 to run task
[2025-01-20T11:10:30.065+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_query_dag', 'fetch_data_from_postgres', 'manual__2025-01-20T11:10:29.293182+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpj8yqmg14']
[2025-01-20T11:10:30.066+0000] {standard_task_runner.py:105} INFO - Job 140: Subtask fetch_data_from_postgres
[2025-01-20T11:10:30.108+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_query_dag.fetch_data_from_postgres manual__2025-01-20T11:10:29.293182+00:00 [running]> on host 7854821b9569
[2025-01-20T11:10:30.157+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_query_dag' AIRFLOW_CTX_TASK_ID='fetch_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T11:10:29.293182+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T11:10:29.293182+00:00'
[2025-01-20T11:10:30.158+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T11:10:30.172+0000] {logging_mixin.py:190} INFO - hello
[2025-01-20T11:10:30.172+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-20T11:10:30.178+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T11:10:30.179+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_query_dag, task_id=fetch_data_from_postgres, run_id=manual__2025-01-20T11:10:29.293182+00:00, execution_date=20250120T111029, start_date=20250120T111030, end_date=20250120T111030
[2025-01-20T11:10:30.241+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-20T11:10:30.256+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-20T11:10:30.262+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
