[2025-01-22T09:19:03.489+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T09:19:03.498+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branching_2.branching manual__2025-01-22T09:19:02.003225+00:00 [queued]>
[2025-01-22T09:19:03.503+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branching_2.branching manual__2025-01-22T09:19:02.003225+00:00 [queued]>
[2025-01-22T09:19:03.503+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-22T09:19:03.512+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): branching> on 2025-01-22 09:19:02.003225+00:00
[2025-01-22T09:19:03.516+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=756) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-22T09:19:03.517+0000] {standard_task_runner.py:72} INFO - Started process 757 to run task
[2025-01-22T09:19:03.517+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branching_2', 'branching', 'manual__2025-01-22T09:19:02.003225+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/b.py', '--cfg-path', '/tmp/tmpdsgskakh']
[2025-01-22T09:19:03.518+0000] {standard_task_runner.py:105} INFO - Job 203: Subtask branching
[2025-01-22T09:19:03.544+0000] {task_command.py:467} INFO - Running <TaskInstance: branching_2.branching manual__2025-01-22T09:19:02.003225+00:00 [running]> on host 7854821b9569
[2025-01-22T09:19:03.590+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branching_2' AIRFLOW_CTX_TASK_ID='branching' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T09:19:02.003225+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T09:19:02.003225+00:00'
[2025-01-22T09:19:03.591+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T09:19:03.599+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-22T09:19:03.606+0000] {python.py:240} INFO - Done. Returned value was: can_drive
[2025-01-22T09:19:03.606+0000] {branch.py:38} INFO - Branch into can_drive
[2025-01-22T09:19:03.607+0000] {skipmixin.py:230} INFO - Following branch ('can_drive',)
[2025-01-22T09:19:03.612+0000] {skipmixin.py:278} INFO - Skipping tasks [('cant_drive', -1)]
[2025-01-22T09:19:03.633+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T09:19:03.633+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=branching_2, task_id=branching, run_id=manual__2025-01-22T09:19:02.003225+00:00, execution_date=20250122T091902, start_date=20250122T091903, end_date=20250122T091903
[2025-01-22T09:19:03.691+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T09:19:03.710+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-22T09:19:03.715+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
