[2025-01-22T09:18:56.840+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T09:18:56.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branching_2.branching manual__2025-01-22T09:18:54.256865+00:00 [queued]>
[2025-01-22T09:18:56.854+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branching_2.branching manual__2025-01-22T09:18:54.256865+00:00 [queued]>
[2025-01-22T09:18:56.855+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-22T09:18:56.865+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): branching> on 2025-01-22 09:18:54.256865+00:00
[2025-01-22T09:18:56.869+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=747) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-22T09:18:56.871+0000] {standard_task_runner.py:72} INFO - Started process 748 to run task
[2025-01-22T09:18:56.871+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branching_2', 'branching', 'manual__2025-01-22T09:18:54.256865+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/b.py', '--cfg-path', '/tmp/tmpzchze1hy']
[2025-01-22T09:18:56.872+0000] {standard_task_runner.py:105} INFO - Job 200: Subtask branching
[2025-01-22T09:18:56.900+0000] {task_command.py:467} INFO - Running <TaskInstance: branching_2.branching manual__2025-01-22T09:18:54.256865+00:00 [running]> on host 7854821b9569
[2025-01-22T09:18:56.954+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branching_2' AIRFLOW_CTX_TASK_ID='branching' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T09:18:54.256865+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T09:18:54.256865+00:00'
[2025-01-22T09:18:56.955+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T09:18:56.963+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-22T09:18:56.972+0000] {python.py:240} INFO - Done. Returned value was: can_drive
[2025-01-22T09:18:56.973+0000] {branch.py:38} INFO - Branch into can_drive
[2025-01-22T09:18:56.974+0000] {skipmixin.py:230} INFO - Following branch ('can_drive',)
[2025-01-22T09:18:56.980+0000] {skipmixin.py:278} INFO - Skipping tasks [('cant_drive', -1)]
[2025-01-22T09:18:57.001+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T09:18:57.001+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=branching_2, task_id=branching, run_id=manual__2025-01-22T09:18:54.256865+00:00, execution_date=20250122T091854, start_date=20250122T091856, end_date=20250122T091857
[2025-01-22T09:18:57.045+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T09:18:57.064+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-22T09:18:57.068+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
