[2025-01-20T11:11:18.256+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T11:11:18.265+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_query_dag.fetch_data_from_postgres manual__2025-01-20T11:11:17.576291+00:00 [queued]>
[2025-01-20T11:11:18.269+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_query_dag.fetch_data_from_postgres manual__2025-01-20T11:11:17.576291+00:00 [queued]>
[2025-01-20T11:11:18.270+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-20T11:11:18.279+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_data_from_postgres> on 2025-01-20 11:11:17.576291+00:00
[2025-01-20T11:11:18.284+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=842) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T11:11:18.285+0000] {standard_task_runner.py:72} INFO - Started process 843 to run task
[2025-01-20T11:11:18.285+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_query_dag', 'fetch_data_from_postgres', 'manual__2025-01-20T11:11:17.576291+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp8l_whcik']
[2025-01-20T11:11:18.286+0000] {standard_task_runner.py:105} INFO - Job 141: Subtask fetch_data_from_postgres
[2025-01-20T11:11:18.315+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_query_dag.fetch_data_from_postgres manual__2025-01-20T11:11:17.576291+00:00 [running]> on host 7854821b9569
[2025-01-20T11:11:18.364+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_query_dag' AIRFLOW_CTX_TASK_ID='fetch_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T11:11:17.576291+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T11:11:17.576291+00:00'
[2025-01-20T11:11:18.365+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T11:11:18.377+0000] {logging_mixin.py:190} INFO - hello
[2025-01-20T11:11:18.377+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-20T11:11:18.383+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T11:11:18.383+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_query_dag, task_id=fetch_data_from_postgres, run_id=manual__2025-01-20T11:11:17.576291+00:00, execution_date=20250120T111117, start_date=20250120T111118, end_date=20250120T111118
[2025-01-20T11:11:18.420+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-20T11:11:18.428+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-20T11:11:18.432+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
